//Action Types
export const GET_LISTS = "GET_LISTS"
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS"
export const GET_LISTS_FAILURE = "GET_LISTS_FAILURE"

export const ADD_LIST = "ADD_LIST"
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS"
export const ADD_LIST_FAILURE = "ADD_LIST_FAILURE"

export const UPDATE_LIST = "UPDATE_LIST"
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS"
export const UPDATE_LIST_FAILURE = "UPDATE_LIST_FAILURE"

export const DELETE_LIST = "DELETE_LIST"
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS"
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE"

export const ADD_TODO = "ADD_TODO"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const UPDATE_TODO = "UPDATE_TODO"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE"

export const DELETE_TODO = "DELETE_TODO"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const SET_SELECTED_LIST_ID = "SET_SELECTED_LIST_ID"
